spring:
  application:
    name: resume-job-matching-backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/resume_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

ml:
  service:
    url: http://localhost:8000

logging:
  level:
    com.resumematcher: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
